export const tokens = {
  MainRouter: Symbol('MainRouter'),
  CustomerRouter: Symbol('CustomerRouter'),
  DocsRouter: Symbol('DocsRouter'),
  FrameworkRouter: Symbol('FrameworkRouter'),
  CreateCustomerController: Symbol('CreateCustomerController'),
  ListCustomerController: Symbol('ListCustomerController'),
  CreateCustomerMiddlewares: Symbol('CreateCustomerMiddlewares'),
  ControllerAdapter: Symbol('ControllerAdapter'),
  DocsController: Symbol('DocsController'),
  CreateCustomerService: Symbol('CreateCustomerService'),
  ListCustomerService: Symbol('ListCustomerService'),
  DocsService: Symbol('DocsService'),
  CustomerRepository: Symbol('CustomerRepository'),
  CustomerValidator: Symbol('CustomerValidator'),
  getCep: Symbol('getCep'),
  isCpfValid: Symbol('isCpfValid'),
  checkUnique: Symbol('checkUnique'),
};
