export const tokens = {
  MainRouter: Symbol('MainRouter'),
  UserRouter: Symbol('UserRouter'),
  DocsRouter: Symbol('DocsRouter'),
  FrameworkRouter: Symbol('FrameworkRouter'),
  CreateUserController: Symbol('CreateUserController'),
  ListUserController: Symbol('ListUserController'),
  CreateUserMiddlewares: Symbol('CreateUserMiddlewares'),
  ControllerAdapter: Symbol('ControllerAdapter'),
  DocsController: Symbol('DocsController'),
  CreateUserService: Symbol('CreateUserService'),
  ListUserService: Symbol('ListUserService'),
  DocsService: Symbol('DocsService'),
  UserRepository: Symbol('UserRepository'),
  UserValidator: Symbol('UserValidator'),
  getCep: Symbol('getCep'),
  isCpfValid: Symbol('isCpfValid'),
  checkUnique: Symbol('checkUnique'),
};
